Rework de los objetos equipables y ajustes a los stats de combate
El-AMPA/MMOTFG pull request #10
Opened 2022-03-09 14:45 UTC by mmur07

**Cambios con equipamiento:**
Se ha resuelto el cacao de los stats al equipar objetos.
Ahora para crear un objeto equipable simplemente los tienes que añadir a su lista de StatModifiers y ya está.
La clase de la que hereda implementa toda la gestión de aplicar estos cambios de stats al equipar/desequipar los objetos.

Cuando te equipas un objeto del inventario, se "consume" y desaparece del inventario.
Del mismo modo, cuando te lo desequipas, se añade al inventario.

He añadido **2 nuevos comandos**: cUnequipGear y cShowGear.

cShowGear es un comando que muestra el objeto que está siendo equipado en una ranura de equipamiento concreta.
Puedes hacer /gear para que muestre lo que el usuario lleva en TODAS las ranuras, o hacer /gear weapon o con cualquier otra ranura para ver lo que lleva en una ranura en concreto.

**Cambios con stats:**
El problema original que llevó a estos cambios es que hacer en este caso:

El jugador tiene 40/50 HP. Se equipa un objeto que te baja la HP máxima en 20 puntos. Si nos diera igual, lo dejaría en 40/30 HP, si fuéramos vagos, lo dejaríamos en 20/20 HP. El problema de esta última solución es qué pasa cuando se desequipa este objeto. ¿Le dejamos en 20/50, le sumo 20 HP por la cara? Sería una solución a un problema que hubiera generado varios problemas adicionales. Sería horrible gestionar los objetos de esta manera porque irías perdiendo vida por todos lados.

Para solucionar esto, cuando una pieza de equipamiento modifica un stat como el MP o el HP, se mantiene el porcentaje de HP o MP que tiene actualmente. Por ejemplo, si estás a 5/10 de HP, estás al 50% de vida. Si te equipas un objeto que suma 6 de vida, tus nuevos valores de vida serían 8/16 HP. Mantienes el porcentaje de vida actual.

**Para probar las nuevas funcionalidades seguid estos pasos:**

- /add tfury
- /add sulfuras
- /status
- /equip tfury
- /status
- /gear weapon
- /gear
- /unequip sulfuras
- /unequip weapon
- /gear weapon
- /equip tfury
- /inventory
- /equip sulfuras
- /inventory

Para ver los cambios de stats id dos salas al norte y pegaros con manuela mientras equipais/desequipais el objeto tfury (mirad la vida actual y maxima)

2022-03-10 10:14 UTC, Pj6595 requested changes
![image](https://user-images.githubusercontent.com/47722275/157640517-1296981a-4b35-461b-b899-25d28020f068.png)

El ataque no me ha subido?

2022-03-10 10:15 UTC, Pj6595 commented on MMOTFG_Bot/MMOTFG_Bot/Commands/cEquipItem.cs
>                  EquipableItem eItem = (EquipableItem)item; //lol. Si funciona doy gracias. O pido perdon.
Mmur deja de poner comentarios de estos te lo pido por favor como vea otra cosa de estas moriré

2022-03-11 11:20 UTC, mmur07 commented on MMOTFG_Bot/MMOTFG_Bot/Commands/cEquipItem.cs
>                  EquipableItem eItem = (EquipableItem)item; //lol. Si funciona doy gracias. O pido perdon.
Que problema tiene?

2022-03-11 11:21 UTC, Pj6595 commented on MMOTFG_Bot/MMOTFG_Bot/Commands/cEquipItem.cs
>                  EquipableItem eItem = (EquipableItem)item; //lol. Si funciona doy gracias. O pido perdon.
//lol. Si funciona doy gracias. O pido perdon.

2022-03-11 11:22 UTC, mmur07 commented on MMOTFG_Bot/MMOTFG_Bot/Commands/cEquipItem.cs
>                  EquipableItem eItem = (EquipableItem)item; //lol. Si funciona doy gracias. O pido perdon.
Ah, pensaba que decias el de arriba

2022-03-11 11:54 UTC, Pj6595 approved these changes

2022-03-11 11:54 UTC, merged