Advanced battle
El-AMPA/MMOTFG pull request #6
Opened 2022-03-03 23:54 UTC by Auraum

Batallas en el mapa, nuevos enemigos, objetos equipables, comandos de info y status, y mucho más

2022-03-04 10:18 UTC, Pj6595 requested changes
Media descripción detallada en el pull aunque sea dale alvar

2022-03-05 11:28 UTC, mmur07 requested changes
Corrigeme si me equivoco pero los cambios de stats de los ataques son permanentes. Deberían deshacerse al terminar la pelea.

2022-03-05 11:33 UTC, mmur07 requested changes
No deberías poder moverte a otra sala mientras estás en una pelea

2022-03-05 11:38 UTC, mmur07 commented
Con lo de los cambios de stats me refiero a que si el enemigo baja el ataque del jugador, este cambio es permanente. Con los enemigos en principio da igual porque son instancias de una clase.

2022-03-06 20:04 UTC, mmur07 approved these changes
Bene

2022-03-06 20:04 UTC, merged